---
theme: jekyll-theme-minimal
title: Andy Vu
description: |
  Digital Curriculum Vitae <br>
  
  [View My Formal Resume](https://andyvu016.github.io/assets/Andy_Vu_Resume.pdf)
---
{{ page.description | markdownify }}
